# Generated by Django 2.2 on 2021-02-26 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('ans_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('answare', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answers', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maal.Answers')),
            ],
        ),
    ]
